vars:
  - cur_folder: 'src/pipelines/example'
  - repo_root: '../../..'
  - params.yaml

stages:
  preprocess:
    cmd: python ${cur_folder}/preprocess.py
    wdir: ${repo_root}
    params:
      - ${cur_folder}/params.yaml:
        - data_config
    outs:
    - ${data_config.data_path}
  train:
    cmd: python ${cur_folder}/train.py
    wdir: ${repo_root}
    params:
      - ${cur_folder}/params.yaml:
        - train_config
    deps:
    - ${data_config.data_path}
    outs:
    - ${train_config.output_path}
  eval:
    cmd: python ${cur_folder}/eval.py
    wdir: ${repo_root}
    deps:
    - ${train_config.output_path}
    outs:
    - ${train_config.log_root}/eval
